# Generated by Django 6.0.5 on 2026-05-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='authorization_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pat_reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('interswitch', 'Interswitch'), ('zest', 'Zest')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
