skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pat = "HopC7DPpeyiPiq2Nqyy9WDCRBKduNu3PoqyaN6ACZUhh"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
