import { useEffect, useState } from "react";
import { useConnection } from "@solana/wallet-adapter-react";
import { availableOffline, nowAdjusted, pendingTotal, phaseOf, reconcileWithChain, type OfflineLedger } from "../lib/ledger";
import { lamportsToSol, shortKey } from "../lib/format";

export function LedgerPanel({ ledger, online, onChange }: { ledger: OfflineLedger; online: boolean; onChange: () => void }) {
  const { connection } = useConnection(); const [msg, setMsg] = useState<string | null>(null); const now = nowAdjusted(ledger);
  async function refresh() { try { await reconcileWithChain(connection, ledger); setMsg("Synced from chain."); onChange(); } catch (e) { setMsg(`Sync failed: ${e instanceof Error ? e.message : String(e)}`); } }
  useEffect(() => { if (online) void refresh(); }, [online]);
  useEffect(() => { if (!online || !ledger.history?.some((h) => h.status === "SIGNED")) return; const id = window.setInterval(() => void refresh(), 15000); return () => window.clearInterval(id); }, [online, ledger.reservation, ledger.history]);
  return <section className="card"><h3>Reservation {shortKey(ledger.reservation)} <span className={`pill ${phaseOf(ledger, now)}`}>{phaseOf(ledger, now)}</span></h3>{!online && <p className="offline-badge">Offline — showing local ledger</p>}<div className="big">{lamportsToSol(availableOffline(ledger))} SOL <small>available offline</small></div><table><tbody><tr><td>Capacity</td><td>{lamportsToSol(BigInt(ledger.capacity))} SOL</td></tr><tr><td>Committed on-chain</td><td>{lamportsToSol(BigInt(ledger.committedOnChain))} SOL</td></tr><tr><td>Pending</td><td>{lamportsToSol(pendingTotal(ledger))} SOL ({ledger.pending.length})</td></tr><tr><td>Per-payment cap</td><td>{lamportsToSol(BigInt(ledger.perPaymentCap))} SOL</td></tr></tbody></table><button onClick={() => void refresh()} disabled={!online}>Refresh from chain</button>{msg && <p className="status">{msg}</p>}<h4>Transaction history</h4><table><thead><tr><th>Time</th><th>Merchant</th><th>Amount</th><th>Status</th></tr></thead><tbody>{[...(ledger.history ?? [])].sort((a, b) => b.createdAt - a.createdAt).map((h) => <tr key={h.paymentId}><td>{new Date(h.createdAt * 1000).toLocaleString()}</td><td>{h.merchant ? shortKey(h.merchant) : "—"}</td><td>{lamportsToSol(BigInt(h.amount))} SOL</td><td><span className={`pill ${h.status}`}>{h.status}</span>{h.failureReason && ` — ${h.failureReason}`}</td></tr>)}</tbody></table></section>;
}
