import localforage from "localforage";
import type { Connection } from "@solana/web3.js";
import type { ReservationAccount } from "./pat";

const store = localforage.createInstance({ name: "pat", storeName: "ledgers" });
export interface PendingIntent { paymentId: string; amount: string; sequence: number; signedAt: number; }
export type HistoryStatus = "SIGNED" | "SETTLED" | "EXPIRED" | "FAILED";
export interface HistoryEntry { paymentId: string; merchant: string; amount: string; createdAt: number; expiresAt: number; sequence: number; memo?: string; status: HistoryStatus; settleSig?: string; settledAt?: number; failureReason?: string; payload?: unknown; }
export interface OfflineLedger { reservation: string; owner: string; capacity: string; perPaymentCap: string; committedOnChain: string; expiresAt: number; settleDeadline: number; pending: PendingIntent[]; history: HistoryEntry[]; nextSequence: number; syncedAt: number; maxPayments?: number; clockOffset?: number; }
export type LedgerErrorCode = "NO_LEDGER" | "RESERVATION_EXPIRED" | "ZERO_AMOUNT" | "OVER_PER_PAYMENT_CAP" | "INSUFFICIENT_OFFLINE_BALANCE";
export class LedgerError extends Error { code: LedgerErrorCode; constructor(code: LedgerErrorCode, message?: string) { super(message ?? code); this.code = code; } }
async function withLock<T>(fn: () => Promise<T>): Promise<T> { if (typeof navigator !== "undefined" && navigator.locks) return navigator.locks.request("pat-ledger", fn) as Promise<T>; return fn(); }
export const pendingTotal = (l: OfflineLedger): bigint => l.pending.reduce((s, p) => s + BigInt(p.amount), 0n);
export const availableOffline = (l: OfflineLedger): bigint => { const v = BigInt(l.capacity) - BigInt(l.committedOnChain) - pendingTotal(l); return v > 0n ? v : 0n; };
export type Phase = "Active" | "Expiring" | "Releasable";
export const phaseOf = (l: OfflineLedger, now: number): Phase => now < l.expiresAt ? "Active" : now <= l.settleDeadline ? "Expiring" : "Releasable";
export const nowAdjusted = (l: OfflineLedger): number => Math.floor(Date.now() / 1000) + (l.clockOffset ?? 0);
export const randomPaymentIdHex = (): string => Array.from(crypto.getRandomValues(new Uint8Array(32)), (b) => b.toString(16).padStart(2, "0")).join("");
export const getLedger = (reservation: string) => store.getItem<OfflineLedger>(reservation);
function migrate(value: OfflineLedger | null): OfflineLedger { if (!value) throw new LedgerError("NO_LEDGER"); const history = value.history ?? (value.pending ?? []).map((p) => ({ paymentId: p.paymentId, merchant: "", amount: p.amount, createdAt: p.signedAt, expiresAt: value.expiresAt, sequence: p.sequence, status: "SIGNED" as const })); return { ...value, history, pending: value.pending ?? history.filter((h) => h.status === "SIGNED").map(({ paymentId, amount, sequence, createdAt }) => ({ paymentId, amount, sequence, signedAt: createdAt })) }; }
export async function listLedgers(owner: string): Promise<OfflineLedger[]> { const out: OfflineLedger[] = []; await store.iterate<OfflineLedger, void>((v) => { if (v.owner === owner) out.push(migrate(v)); }); return out.sort((a, b) => b.expiresAt - a.expiresAt); }
export const deleteLedger = (reservation: string) => store.removeItem(reservation);
export function initLedgerIfAbsent(reservation: string, acct: ReservationAccount, metadata?: Pick<OfflineLedger, "maxPayments" | "clockOffset">): Promise<OfflineLedger> { return withLock(async () => { const existing = await store.getItem<OfflineLedger>(reservation); if (existing) return migrate(existing); const ledger: OfflineLedger = { reservation, owner: acct.owner.toBase58(), capacity: acct.capacity.toString(), perPaymentCap: acct.perPaymentCap.toString(), committedOnChain: acct.committed.toString(), expiresAt: Number(acct.expiresAt), settleDeadline: Number(acct.settleDeadline), pending: [], history: [], nextSequence: 0, syncedAt: Math.floor(Date.now() / 1000), ...metadata }; await store.setItem(reservation, ledger); return ledger; }); }
export function refreshCommitted(reservation: string, acct: ReservationAccount): Promise<OfflineLedger> { return withLock(async () => { const l = await store.getItem<OfflineLedger>(reservation); if (!l) throw new LedgerError("NO_LEDGER"); l.committedOnChain = acct.committed.toString(); l.syncedAt = Math.floor(Date.now() / 1000); await store.setItem(reservation, l); return l; }); }
export function debitForPayment(reservation: string, req: { paymentId: string; amount: bigint }, now: number): Promise<{ sequence: number; committedAfter: bigint }> { return withLock(async () => { const l = migrate(await store.getItem<OfflineLedger>(reservation)!); if (!l) throw new LedgerError("NO_LEDGER"); if (now >= l.expiresAt) throw new LedgerError("RESERVATION_EXPIRED"); if (req.amount <= 0n) throw new LedgerError("ZERO_AMOUNT"); if (req.amount > BigInt(l.perPaymentCap)) throw new LedgerError("OVER_PER_PAYMENT_CAP"); if (req.amount > availableOffline(l)) throw new LedgerError("INSUFFICIENT_OFFLINE_BALANCE"); const sequence = l.nextSequence; const committedAfter = BigInt(l.committedOnChain) + pendingTotal(l) + req.amount; l.pending.push({ paymentId: req.paymentId, amount: req.amount.toString(), sequence, signedAt: now }); l.nextSequence += 1; await store.setItem(reservation, l); return { sequence, committedAfter }; }); }
export async function addHistoryEntry(reservation: string, entry: HistoryEntry): Promise<OfflineLedger> { return withLock(async () => { const l = migrate(await store.getItem<OfflineLedger>(reservation)!); if (!l) throw new LedgerError("NO_LEDGER"); l.history = [...l.history.filter((x) => x.paymentId !== entry.paymentId), entry]; await store.setItem(reservation, l); return l; }); }
export async function rollbackPending(reservation: string, paymentId: string): Promise<OfflineLedger> { return withLock(async () => { const l = migrate(await store.getItem<OfflineLedger>(reservation)!); if (!l) throw new LedgerError("NO_LEDGER"); l.pending = l.pending.filter((p) => p.paymentId !== paymentId); l.history = l.history.filter((h) => h.paymentId !== paymentId); await store.setItem(reservation, l); return l; }); }
export async function markSettled(reservation: string, paymentId: string, settleSig?: string, settledAt = Math.floor(Date.now() / 1000)): Promise<OfflineLedger> { return withLock(async () => { const l = migrate(await store.getItem<OfflineLedger>(reservation)!); if (!l) throw new LedgerError("NO_LEDGER"); l.history = l.history.map((h) => h.paymentId === paymentId ? { ...h, status: "SETTLED", settleSig, settledAt } : h); l.pending = l.pending.filter((p) => p.paymentId !== paymentId); await store.setItem(reservation, l); return l; }); }
export async function markExpired(reservation: string, paymentId: string): Promise<OfflineLedger> { return withLock(async () => { const l = migrate(await store.getItem<OfflineLedger>(reservation)!); if (!l) throw new LedgerError("NO_LEDGER"); l.history = l.history.map((h) => h.paymentId === paymentId ? { ...h, status: "EXPIRED" } : h); l.pending = l.pending.filter((p) => p.paymentId !== paymentId); await store.setItem(reservation, l); return l; }); }
export async function reconcileWithChain(_connection: Connection, ledger: OfflineLedger): Promise<OfflineLedger> { const updated = migrate(ledger); const now = nowAdjusted(updated); updated.history = updated.history.map((h) => h.status === "SIGNED" && now > h.expiresAt ? { ...h, status: "EXPIRED" } : h); updated.pending = updated.history.filter((h) => h.status === "SIGNED").map((h) => ({ paymentId: h.paymentId, amount: h.amount, sequence: h.sequence, signedAt: h.createdAt })); await store.setItem(updated.reservation, updated); return updated; }
export function __ledgerStoreForTests() { return { store }; }
